# Generated by Django 4.1.6 on 2023-03-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MajorMinors',
            new_name='MajorOrMinor',
        ),
    ]
