# Generated by Django 4.1.6 on 2023-03-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_advstudconn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major1', to='base.majororminor')),
                ('major2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major2', to='base.majororminor')),
                ('minor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor1', to='base.majororminor')),
                ('minor2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor2', to='base.majororminor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsMajors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
