# Generated by Django 4.1.6 on 2023-03-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('data', models.TextField()),
                ('result', models.BooleanField(null=True)),
                ('adv_stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.advstudconn')),
            ],
        ),
    ]
