# Generated by Django 4.1.6 on 2023-03-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('professor', models.TextField()),
                ('days', models.TextField()),
                ('num_credits', models.TextField()),
                ('maj_min', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.majororminor')),
            ],
        ),
    ]
