# Generated by Django 4.1.6 on 2023-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
        migrations.AlterField(
            model_name='course',
            name='num_credits',
            field=models.IntegerField(),
        ),
    ]
