# Generated by Django 4.1.6 on 2023-03-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_requests_request_alter_course_num_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('course1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='base.course')),
                ('course2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='base.course')),
                ('course3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='base.course')),
                ('course4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='base.course')),
                ('course5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='base.course')),
                ('course6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='base.course')),
                ('course7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='base.course')),
                ('course8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course8', to='base.course')),
            ],
        ),
    ]
