# Generated by Django 4.1.6 on 2023-03-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='course1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course8', to='base.course'),
        ),
    ]
