# Generated by Django 4.1.6 on 2023-03-19 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_semester_course1_alter_semester_course2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchedMajor1', to='base.majororminor')),
                ('major2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchedMajor2', to='base.majororminor')),
                ('minor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchedMinor1', to='base.majororminor')),
                ('minor2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchedMinor2', to='base.majororminor')),
                ('semester1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester1', to='base.semester')),
                ('semester10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester10', to='base.semester')),
                ('semester2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester2', to='base.semester')),
                ('semester3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester3', to='base.semester')),
                ('semester4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester4', to='base.semester')),
                ('semester5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester5', to='base.semester')),
                ('semester6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester6', to='base.semester')),
                ('semester7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester7', to='base.semester')),
                ('semester8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester8', to='base.semester')),
                ('semester9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester9', to='base.semester')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentSched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
