# Generated by Django 4.1.6 on 2023-03-21 17:20

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_majororminor_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major1', to='base.majororminor', validators=[base.models.validate_major]),
        ),
        migrations.AlterField(
            model_name='student',
            name='major2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major2', to='base.majororminor', validators=[base.models.validate_major]),
        ),
    ]
