# Generated by Django 4.1.6 on 2023-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_schedule_major1_alter_schedule_major2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.TextField(blank=True, default='unnamed_schedule'),
        ),
    ]
