# Generated by Django 4.1.6 on 2023-04-03 17:42

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_subject_request_req_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='major1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchedMajor1', to='base.majororminor', validators=[base.models.validate_major]),
        ),
    ]
