# Generated by Django 4.1.6 on 2023-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_schedule_major1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='major1',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='major2',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minor1',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minor2',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
