# Generated by Django 4.1.6 on 2023-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_schedule_major1_alter_schedule_major2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.TextField(default='unnamed'),
        ),
    ]
