# Generated by Django 4.1.6 on 2023-04-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_semester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='req_subject',
            new_name='subject',
        ),
    ]
