# Generated by Django 4.1.6 on 2023-04-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_req_subject_request_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
