# Generated by Django 4.1.6 on 2023-04-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='semester10',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester9',
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester0', to='base.semester'),
        ),
    ]
