# Generated by Django 4.1.6 on 2023-04-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_advstudconn_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='name',
            new_name='label',
        ),
    ]
